### ISSUE TITLE
Switch Like Home and More Library Icons bugs.

### ISSUE THREAD

**Issue by outerwinnie** [suchmememanyskill/CssLoader-ThemeDb#47] opened 2022-08-08 22:23 UTC
Hi, i have found a couple of bugs.

The Switch Like Home theme, seems to displace and not fit correctly after entering in a game library page and coming back to home:
https://streamable.com/hk2che

And the "More Library Icons" theme doesn't seems to load all the icons that should be (at least not at the pace that it should):
https://streamable.com/8vzkk0

Sorry if this isn't the place to post bugs from the themes, but i couldn't find any other place.

**Comment by suchmememanyskill** [comment] 2022-08-09 00:20
Hi, i think placing bugs here is fine, the relevant people can get pinged

The switch like home theme is a bug when specifically you both have round **and** switch like home active

The more library icons thing i don't think i can fix as it's probably controlled by js

**Comment by EMERALD0874** [comment] 2022-08-09 00:41
As the creator of Round, I can confirm it's most likely due to you using the round outlines. They use a different type of outline in CSS, causing margins to be slightly off when using specific other themes.

I'm closing this issue because it's pertinent to themes within the database, not the database itself. You can definitely report this as a bug on the repo for Round if you'd like.

**Closed as not planned by EMERALD0874** 2022-08-09 00:41 UTC

**Comment by outerwinnie** [comment] 2022-08-09 01:21
Thanks, will move it there!
